config/routes.rb
Rails.application.routes.draw do
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  get '/' => 'homes#top' ,as: 'root'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
      flash[:create]="Book was successfully created."
    else
      @books = Book.all
      render 'index'
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:update]="Book was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <div class="error">
    <h2><%= @book.errors.count %> errors prohibited this book from beging saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local: true do |f| %>

<div class="edit-item">
  <p>Title</p>
  <%= f.text_field :title %>
</div>
<div class="edit-item">
  <p>Body</p>
  <%= f.text_area :body %>
</div>
<div class="edit-item">
  <%= f.submit 'Update Book' , class: 'submit' %>
</div>
<%= link_to "Show", book_path(@book.id) , class: 'cursor' %>
|
<a class="link" href="/books" class="cursor">Back</a>

<% end %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) , class: 'cursor' %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) , class: 'cursor' %></td>
      <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" , class: 'cursor' %></td>
    </tr>
  <% end %>
</table>


<h2>New book</h2>


<% if @book.errors.any? %>
  <div class="error">
   <h2><%= @book.errors.count %> errors prohibited this book from beging saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @book, local:true do |f| %>
<div class="field">
  <div class="form">
    <label>Title</label>
    <%= f.text_field :title %>
  </div>
</div>

<div class="field">
  <div class="form">
    <label>Body</label>
    <%= f.text_area :body %>
  </div>
</div>

    <%= f.submit "Create Book" , class: 'submit' %>

<% end %>

app/views/books/show.html.erb
<p class="flash"><%= flash[:create] %></p>

<p class="flash"><%= flash[:update] %></p>

<p class="show">
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p class="show">
  <strong>Body:</strong>
  <%= @book.body %>
</p>

  <p>
    <%= link_to "Edit", edit_book_path(@book.id) , class: 'cursor' %>
    |
    <a class="link" href="/books" class="cursor">Back</a>
  </p>

app/views/homes/top.html.erb
<h1>
  ようこそ
  <strong>Bookers</strong>
  へ！
</h1>

<p class="top">
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>

<p class="top">
  印象を共有し交換することができます
</p>

<p class="top">
  <%= link_to "start", books_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>